apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: GCSBucket
metadata:
  name: test8
  labels:
    org: AMC
    env: Stage
    region: asia-south1
    project: stage-gmf-applayer-43e8
    cluster: stage-gmf-cluster
    cloud: gcp
    datacenter: primary
    pod: AMC
    tier: t1
    cell: none
    function: bucket
spec:
  location: ASIA-SOUTH1